package cn.gloduck.api.exceptions;

public enum ApiError {
    DATA_NOT_FOUND,
    OPERATION_FAILED,
    INTERNAL_SERVER_ERROR,
    INVALID_PARAMETER,

    TORRENT_SOURCE_UNSUPPORTED,
    TORRENT_REQUEST_FAILED,
    TORRENT_RESPONSE_INVALID,
    TORRENT_INFO_NOT_FOUND,
    TORRENT_HASH_NOT_FOUND,

    CLIPBOARD_SAVE_FAILED,
    CLIPBOARD_NOT_FOUND,

    SSH_SECURITY_KEY_INVALID,
    SSH_CONNECT_REQUIRED,
    SSH_CONNECT_REQUEST_INVALID,
    SSH_CONNECT_FAILED,
    SSH_CONNECTION_LIMIT_EXCEEDED,
    SSH_CONNECTION_UNAVAILABLE,
    SSH_MESSAGE_INVALID,
    SSH_MESSAGE_TYPE_UNSUPPORTED,
    SSH_CONNECTION_DISCONNECTED,
    SSH_HEARTBEAT_TIMEOUT,

    SFTP_REQUEST_INVALID,
    SFTP_UPLOAD_FAILED,
    SFTP_DOWNLOAD_FAILED,
    SFTP_REMOTE_PATH_INVALID,

    PROXY_HOST_REQUIRED,
    PROXY_TARGET_INVALID,
    PROXY_REDIRECT_BODY_UNSUPPORTED,
    PROXY_REQUEST_FAILED
}
